// <auto-generated />
using KartKitabch.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KartKitabch.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260709035035_DataBaseKart")]
    partial class DataBaseKart
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KartKitabch.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyTon")
                        .HasColumnType("int");

                    b.Property<int>("MyProperty")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("KartKitabch.Models.CompanyLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("ProvincesAndCitiesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ProvincesAndCitiesId");

                    b.ToTable("CompanyLocations");
                });

            modelBuilder.Entity("KartKitabch.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("KartKitabch.Models.ProvincesAndCities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProvincesAndCities");
                });

            modelBuilder.Entity("KartKitabch.Models.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Chasis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("DateS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DestinationCompanyId")
                        .HasColumnType("int");

                    b.Property<int?>("DestinationProvinceId")
                        .HasColumnType("int");

                    b.Property<int?>("KartDuration")
                        .HasColumnType("int");

                    b.Property<int?>("KartNewRenewLost")
                        .HasColumnType("int");

                    b.Property<string>("PaletNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.Property<int?>("ProvincesAndCitiesId")
                        .HasColumnType("int");

                    b.Property<int?>("ReportId")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TypeOfActivity")
                        .HasColumnType("int");

                    b.Property<int?>("TypeOfKart")
                        .HasColumnType("int");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DestinationCompanyId");

                    b.HasIndex("DestinationProvinceId");

                    b.HasIndex("PersonId");

                    b.HasIndex("ProvincesAndCitiesId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Report");
                });

            modelBuilder.Entity("KartKitabch.Models.vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("KartKitabch.Models.CompanyLocation", b =>
                {
                    b.HasOne("KartKitabch.Models.Company", "Company")
                        .WithMany("CompanyLocations")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KartKitabch.Models.ProvincesAndCities", "ProvincesAndCities")
                        .WithMany()
                        .HasForeignKey("ProvincesAndCitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("ProvincesAndCities");
                });

            modelBuilder.Entity("KartKitabch.Models.Report", b =>
                {
                    b.HasOne("KartKitabch.Models.Company", "Company")
                        .WithMany("Report")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KartKitabch.Models.Company", "DestinationCompany")
                        .WithMany()
                        .HasForeignKey("DestinationCompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KartKitabch.Models.ProvincesAndCities", "DestinationProvince")
                        .WithMany()
                        .HasForeignKey("DestinationProvinceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KartKitabch.Models.Person", null)
                        .WithMany("Reports")
                        .HasForeignKey("PersonId");

                    b.HasOne("KartKitabch.Models.ProvincesAndCities", "ProvincesAndCities")
                        .WithMany()
                        .HasForeignKey("ProvincesAndCitiesId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KartKitabch.Models.vehicle", "Vehicle")
                        .WithMany("Reports")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("DestinationCompany");

                    b.Navigation("DestinationProvince");

                    b.Navigation("ProvincesAndCities");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("KartKitabch.Models.Company", b =>
                {
                    b.Navigation("CompanyLocations");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("KartKitabch.Models.Person", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("KartKitabch.Models.vehicle", b =>
                {
                    b.Navigation("Reports");
                });
#pragma warning restore 612, 618
        }
    }
}
